import { Resend } from 'resend';
import { NextResponse } from 'next/server';

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(request) {
    try {
        const { childName, parentEmail, totalHours, totalCost, pdfBase64, fileName } = await request.json();

        // Validate required fields
        if (!childName || !parentEmail || !pdfBase64) {
            return NextResponse.json(
                { error: 'Missing required fields' },
                { status: 400 }
            );
        }

        // Convert base64 to buffer
        const base64Data = pdfBase64.split(',')[1]; // Remove data:application/pdf;base64, prefix
        const pdfBuffer = Buffer.from(base64Data, 'base64');

        // Get current month/year for email
        const currentDate = new Date();
        const monthYear = currentDate.toLocaleDateString('en-GB', {
            month: 'long',
            year: 'numeric'
        });

        // Send email with Resend
        const data = await resend.emails.send({
            from: process.env.RESEND_FROM_EMAIL || 'invoices@yourdomain.com',
            to: parentEmail,
            subject: `Invoice for ${monthYear} - ${childName}`,
            html: `
                <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
                    <h2 style="color: #3b82f6;">Childcare Invoice</h2>
                    <p>Dear Parent/Guardian,</p>
                    <p>Please find attached the invoice for <strong>${childName}</strong> for the period of <strong>${monthYear}</strong>.</p>

                    <div style="background-color: #f3f4f6; padding: 20px; border-radius: 8px; margin: 20px 0;">
                        <p style="margin: 0;"><strong>Total Hours:</strong> ${totalHours.toFixed(2)} hours</p>
                        <p style="margin: 10px 0 0 0; font-size: 18px;"><strong>Total Amount Due:</strong> <span style="color: #3b82f6;">£${totalCost}</span></p>
                    </div>

                    <p>Payment is due within 7 days of the invoice date.</p>
                    <p>If you have any questions regarding this invoice, please don't hesitate to contact me.</p>

                    <p style="margin-top: 30px;">
                        Thank you for your business!<br/>
                        <strong>Your Childminding Service</strong>
                    </p>

                    <hr style="margin: 30px 0; border: none; border-top: 1px solid #e5e7eb;"/>
                    <p style="font-size: 12px; color: #6b7280;">
                        This is an automated email. The attached invoice was generated by our childminding management system.
                    </p>
                </div>
            `,
            attachments: [
                {
                    filename: fileName,
                    content: pdfBuffer,
                },
            ],
        });

        return NextResponse.json({
            success: true,
            messageId: data.id
        });

    } catch (error) {
        console.error('Error sending invoice email:', error);
        return NextResponse.json(
            {
                error: 'Failed to send invoice email',
                details: error.message
            },
            { status: 500 }
        );
    }
}
